[build]
builder = "nixpacks"

[deploy]
startCommand = "python bot.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.envVars]]
key = "WEBHOOK_URL"
value = "https://your-app-name.railway.app"
